name: Easycontrol_For_Car

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    #  将 Base64 恢复为 Keystore 文件
    - name: Decode Keystore
      working-directory: ./easycontrol/app
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks ; find ./  -name "keystore.jks" |xargs ls -lh  

    - name: Build the app
      working-directory: ./easycontrol
      #  执行 assembleRelease，并传入 Secret 环境变量
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: |
        chmod +x gradlew
        ./gradlew :server:copyRelease --stacktrace
        ./gradlew :app:assembleRelease --stacktrace
        find ./easycontrol/app/build/outputs/  -name "*.apk" |xargs ls -lh 
        
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Easycontrol_For_Car_Release
        # 指向 release 目录
        path: ./easycontrol/app/build/outputs/apk/release/*.apk
